apiVersion: v1
kind: Service
metadata:
  name: notes-blue-green-service
  namespace: notes-user-deploy
spec:
  type: NodePort
  ports:
  - nodePort: 30166
    port: 111
    targetPort: 80
    protocal: TCP
  - nodeport: 30177
    port: 112
    targetPort: 81
    protocol: TCP
  selector:
    role: target-role

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-blue-green-deply-ingress
  namespace: notes-user-deploy
spec:
  rules:
  - host: 172.29.87.227
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notes-blue-green-service
            port:
              number: 111
              number: 112
  ingressClassName: nginx
